"use client";

import { useEffect } from "react";

// Registers the Workbox service worker generated by next-pwa.
// Runs on the client only (service workers require a browser).
export default function SWRegister() {
  useEffect(() => {
    if (!("serviceWorker" in navigator)) return;

    navigator.serviceWorker
      .register("/sw.js", { scope: "/" })
      .then((registration) => {
        // Let a newly installed service worker take control immediately,
        // so users always run the freshest cached app.
        registration.addEventListener("updatefound", () => {
          const installing = registration.installing;
          installing?.addEventListener("statechange", () => {
            if (installing.state === "installed" && navigator.serviceWorker.controller) {
              navigator.serviceWorker.controller.postMessage({ type: "SKIP_WAITING" });
            }
          });
        });
      })
      .catch((err) => {
        // Don't crash the app if the worker can't be registered (e.g. offline dev).
        if (process.env.NODE_ENV !== "production") console.warn("SW registration failed:", err);
      });
  }, []);

  return null;
}